---
date: "2018-12-13T00:00:00Z"
external_link: ""
image:
  caption: Cardboard and Foam Model of Civic Center and Library at MG Marg, Gangtok, India
  focal_point: Smart
links:
- icon: twitter
  icon_pack: fab
  name: Follow
  url: https://twitter.com/aseemvd
slides: archi_portfolio
summary: A Portfolio of Undergraduate Architecture and Urban Design Work
tags:
- Architecture and Urban Design
- Academic
- Undergraduate Work
title: Undergraduate Design Portfolio
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""
---

The Undergraduate Portfolio contains curated design documentation of three key projects completed between 2014 and 2016. All three projects contain elements relevant to the study of urban space, and the human interactions that create these spaces.

Please click on the *slides* button above or [here](/slides/archi_portfolio/#/) to see the portfolio pages.

**Civic Institutions as Catalysts for Urban Rejuvenation**

Thesis | Year 5 Semester 2

The project eveolved out of a need to establish cultural institutions while simultaneously addressing issues of urban decay and irregular land utilisation. The development of an active public space was acheived through design interventions which are human in scale
and proportion.

There was a need therefore for the development of an active public space which could complement the existing pedestrian plaza of MG Marg for urban rejuvenation.

**Sakaalnagar - Residential Redevelopment & Upgradation**

Mass Housing | Year 4 Semester 1

Sakaalnagar is a 30 year old housing complex in Pune built when construction materials available were of poor quality. A proposal to redevelop it was finalized in 2013, and our studio took it up as an academic project.

The design philosophy stems from Eyes on the Streets, and Liveable Neighbourhoods concepts aiming to reduce social distances and increase social cohesion and the idea of shared security.

Separate pedestrian and vehicular corridors ensures the safety of residents, playing children and the vulnerable.

**Questioning Urban Paradigms - Studying the Changing Face of Tulshibaug**

Research Dissertation | Year 4 Semester 2

This research aims at understanding the reason for the development of the urban areas of Tulshibaug and Mandai. The architecture and urban patterns of a particular era are a reflection of the social, cultural, economic and political situation prevalent at that time. This has often resulted in an entire city’s character being changed or even the cultural attitudes of its people. 

The purpose of this study is to understand the reasons for this situation, both historical and current. 

It aims at evolving certain design andd policy solutions to improve the present day situation by understanding the needs of all stakeholders including but not limited to shoppers, tourists, worshippers, shopkeepers, and residents.