---
date: "2020-03-20T00:00:00Z"
external_link: ""
image:
  caption: Downtown Boston
  focal_point: Smart
links:
- icon: twitter
  icon_pack: fab
  name: Follow
  url: https://twitter.com/aseemvd
slides: hosp_workers
summary: Exploratory Analysis to Develop Potential Transit Corridors Between Homes and Workplaces of Hospital Workers
tags:
- Spatial Analysis
- Transit and Transportation
- Academic
- BARI
- Graduate Work
- MBTA
- Personal Work
title: Developing Transit Corridors for Hospital Workers
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""
---

# A Study To Develop Transit Corridors for Healthcare Workers between Home and Work

After the declaration of Stay at Home orders or guidelines across the world, transit use has plummeted across all regions. The MBTA experienced almost an [80% drop in service usage](https://www.mbtabackontrack.com/blog/blog/117-covid-19-and-mbta-ridership-part4) use following such guidelines in the Commonwealth of Massachusetts.

This means that approximately 20% of users are still riding. Who are these 20%? They are people who's occupations have been classified as 'Essential Services', and include everyone who cannot do their job sitting at home.

Among these essential workers, are also healthcare workers - who deal with and handle patients afflicted with Covid-19 everyday. Without wanting to add to the mess of visualizations populating the data world out there, in what way could I still contribute? 

In case of prolonged and/or heightened intensity of the current crisis, as well as possible future crises, how can this unique requirement be addressed? Can we develop dedicated transportation services for healthcare workers between home and work?

This is a project under development, using data shared by the generous folks at the [Transit App](https://transitapp.com/) for research purposes only. Due to the proprietary and potentially identifiable nature of these data, I of course cannot share them with you, but if you have any ideas for the way this project may potentially take shape, please send me an email, and I would love to figure out a way to collaborate!